server:
  port: 80
  context-path: /

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 9000

eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责及时维护服务实例,它并不需要去检索服务,所以设置为false
    service-url:
      defaultZone: http://eureka2001.wangshao.com:2001/eureka/,http://eureka2002.wangshao.com:2002/eureka/,http://eureka2003.wangshao.com:2003/eureka/
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

