server:
  port: 91
  context-path: /


eureka:
  client:
    service-url:
      defaultZone: http://eureka2001.wangshao.com:2001/eureka/,http://eureka2002.wangshao.com:2002/eureka/,http://eureka2003.wangshao.com:2003/eureka/


  turbine:
    app-config: microservice-student #指定要监控的应用名称
    clusterNameExpression: "default"  # 表示集群的名字为default

  spring:
    application:
      name: turbine