server:
  port: 1001
  context-path: /

#数据源配置
spring:
  application:
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/db_springcloud?useSSL=false
    username: root
    password:


jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

eureka:
  instance:
    hostname: localhost #eureka客户端主机实例名称
    appname: microservice-student #客户端服务名
    instance-id: microservice-student:1001 #客户端实例名称
    prefer-ip-address: true #显示ip

  client:
    service-url:
      #单机 defaultZone: http://localhost:2001/eureka #把服务注册到eureka中心
      defaultZone: http://eureka2001.wangshao.com:2001/eureka/,http://eureka2002.wangshao.com:2002/eureka/,http://eureka2003.wangshao.com:2003/eureka/ #集群
info:
  groupid: $project.groupId$
  artifactid: $project.artifactId$
  version: $project.version$
  负责人: 张三
  联系电话: 110
