server:
  port: 3001
  context-path: /

spring:
  application:
    name: microservice-zuul
eureka:
  instance:
    instance-id: microservice-zuul:3001 #客户端实例名称
    prefer-ip-address: true #显示ip

  client:
    service-url:
      defaultZone: http://eureka2001.wangshao.com:2001/eureka/,http://eureka2002.wangshao.com:2002/eureka/,http://eureka2003.wangshao.com:2003/eureka/ #集群

info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version: $project.version$
  负责人: 王五
  联系电话: 110

#服务名称 映射
zuul:
  routes:
    studentServer.serviceId: microservice-student
    studentServer.path: /studentServer/**
  ignored-services: "*"
  prefix: /wangshao