server:
  port: 4001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yishanerguo/test
          skip-ssl-validation: true
          search-paths:
            -aaa
            -bbb
